export const weatherCode = {
  0: 'Clear Sky',
  1: 'Mainly Clear',
  2: 'Partly Cloudy',
  3: 'Overcast',
  45: 'Fog',
  48: 'Depositing Rime Fog',
  51: 'Light Drizzle',
  52: 'Moderate Drizzle',
  53: 'Heavy Drizzle',
  56: 'Freezing Light Drizzle',
  57: 'Freezing Dense Drizzle',
  61: 'Slight Rain',
  63: 'Moderate Rain',
  65: 'Heavy Rain',
  66: 'Freezing Light Rain',
  67: 'Freezing Heavy Rain',
  71: 'Slight Snow',
  73: 'Moderate Snow',
  75: 'Heavy Snow',
  77: 'Snow grains',
  80: 'Slight Rain Showers',
  81: 'Moderate Rain Showers',
  82: 'Violent Rain Showers',
  95: 'Thunderstorms',
  96: 'Thunderstorms with Rain',
  99: 'Thunderstorms with Hail',
}
